# Generated by Django 4.0.1 on 2022-09-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0002_table_is_active_table_is_reserved'),
        ('food', '0003_alter_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ManyToManyField(related_name='orders', to='food.Food')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_all_order_this_table', to='table.table')),
            ],
        ),
    ]
