# Generated by Django 4.0.1 on 2022-09-06 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_is_active_table_is_reserved'),
        ('order', '0002_order_count_remove_order_food_order_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('orders', models.ManyToManyField(to='order.Order')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.table')),
            ],
        ),
    ]
