# Generated by Django 4.0.1 on 2022-09-06 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_tableorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 9, 6, 19, 37, 37, 938419, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableorder',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 9, 6, 19, 37, 44, 219064, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
