# Generated by Django 4.0.1 on 2022-09-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorder',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
