# Generated by Django 4.0.1 on 2022-09-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_is_active_table_is_reserved'),
        ('order', '0006_alter_tableorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorder',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables_orders', to='table.table'),
        ),
    ]
