# Generated by Django 4.0.1 on 2022-09-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
